### ISSUE TITLE
extrinsic_calibration_manager can‘t find!

### ISSUE THREAD

**Issue by 0116lhc** [tier4/CalibrationTools#169]
The package extrinsic_calibration_manager cannot be found in the sensor folder. I've pulled the code several times but it's still missing. Could you please confirm the location of this package?

**Comment by knzo25** [comment]
Hi, that is because the extrinsic calibration manager is no longer.
Now we have a different one called sensor calibration manager, but the documentation is currently being written in https://github.com/tier4/CalibrationTools/pull/164

**Comment by yoepav** [comment]
Hello Kenzo,

Can I follow the current documentation for manual calibration and change the steps regarding the extrinsic_calibration_manager directory for the sensor_calibration_manager directory?

**Comment by knzo25** [comment]
Hi,
Thank you for using our tools. Sadly, I am not the maintainer of the manual calibration tool, so its use under the new scheme will need to wait until the maintainer ports the tool to the new API (or, if you prefer, you could use a previous version of the repository that is compatible with the manual tool)

**Comment by yoepav** [comment]
Hi Kenzo,

I tried using the main branch instead of the tier4/universe branch but sadly that doesn't work. So I guess I'll have to wait for the port. Thank you very much anyway.

**Comment by davbt** [comment]
Hi @yoepav & @0116lhc,

The latest Autoware.Universe repo had some package renaming, which causes the rosdep dependency issues you've listed.

~I've forked the CalibrationTools repo with the correct dependency package naming and no longer experience the dependency issues. My fork also reverted to the older version CalibrationTools (i.e. with `extrinsic_calibration_manager` and `aip_x1` directory). I hope this can be useful untill the re-written calibration docs are ready.~

Fork no longer needed, see below

**Comment by TimDing-aoi** [comment]
> Hi @yoepav & @0116lhc,
> 
> The latest Autoware.Universe repo had some package renaming, which causes the rosdep dependency issues you've listed.
> 
> I've [forked the CalibrationTools](https://github.com/dtonda8/CalibrationTools) repo with the correct dependency package naming and no longer experience the dependency issues. My fork also reverted to the older version CalibrationTools (i.e. with `extrinsic_calibration_manager` and `aip_x1` directory). I hope this can be useful untill the re-written calibration docs are ready.

Hello dtonda, thanks for the upload, I have tried your version of the calibration tools but fails to colcon build. 
![Screenshot from 2024-08-15 14-01-22](https://github.com/user-attachments/assets/1960f18e-df08-4b75-919b-f3e46c1939b3)
Do you know what might be the reason for this?

**Comment by davbt** [comment]
Hi @TimDing-aoi, I've created a new issue for [this in my fork](https://github.com/dtonda8/CalibrationTools/issues/1) (it's most likely due to Calibration repos referring to incorrect package naming). If you find out where exactly the issue lies and resolve it, you can create a pr. I will also look into this when I am free.

Edit: rosdep issues resolved, `colcon build` should work

**Comment by knzo25** [comment]
@dtonda8 
I am pretty sure the code in this PR works
https://github.com/tier4/CalibrationTools/pull/164

**Comment by davbt** [comment]
Yes, that pr seems to work. The only issue is that you'll need to switch to a slightly older version of autoware.universe, otherwise the output of `rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO` is this:
![Pasted image 20240820075540](https://github.com/user-attachments/assets/4c7c6b87-b61f-468e-a2cf-107521a324cf)


Autoware.universe recently renamed `kalman_filter` to `autoware_kalman_filter` in this [commit](https://github.com/autowarefoundation/autoware.universe/commit/2f392a849c7f93d2bb0b1305dec1fa2d9a5bd099)
So we should `git checkout` to a commit before that ([fd09a5b](https://github.com/autowarefoundation/autoware.universe/commit/fd09a5bb1daea52afbe2bea11402f87e3d7eb339))
![Pasted image 20240820080520](https://github.com/user-attachments/assets/0f442956-b376-4f1f-a860-2f02bca7ce64)

**Comment by knzo25** [comment]
@dtonda8 
I just updated the PR branch to be compatible with the latest universe (https://github.com/tier4/CalibrationTools/pull/164/commits/1dfc8d72728fb32867fb88af8ee954d6aae62c34)

**Comment by davbt** [comment]
@knzo25 Legend! Thanks for doing that. To everyone else looking for a CalibrationTools version compatible with the latest Autoware and matches the current `extrinsic_calibration_manager` docs, please use knzo25's pr branch.

**Comment by knzo25** [comment]
These issues should disappear in the main branch now
https://github.com/tier4/CalibrationTools/pull/164
