### ISSUE TITLE
Calibrating base-link to Lidar

### ISSUE THREAD

**Issue by ismetatabay** [tier4/CalibrationTools#76]
Hi, I have a question about base-link to main lidar calibration. We are trying create sensor_model for our vehicle. We done camera intrinsic calibrations, lidar - lidar calibrations and camera lidar calibrations. Now, we want calibrating base-link lidar calibration.

To launch extrinsic ground-plane calibration tool, the command is:
```
ros2 launch extrinsic_calibration_manager calibration.launch.xml \
  mode:=ground_plane sensor_model:=<sensor_model> vehicle_model:=<vehicle_model> vehicle_id:=<vehicle_id>
```
This tool uses sensor_model, but we don't have sensor model, because its includes base-link to lidar calibration transformations which we don't have.

How can I calibrate this base-link to lidar calibration?  I should use ```Extrinsic Manual Calibration``` mode for initial calibration?

Thank you in advance.

**Comment by knzo25** [comment]
Hi, thank you for your interest in our tools.

In order to help you, I think it would be convenient to know more about the architecture of sensors you are considering (i.e., the tf tree).

Take consideration that in the simplest case, where only the `base_link`, `sensor_kit`, and the `lidar_frame` exist, the calibrator will perform `base_link` to `lidar_frame` calibration. The `sensor_kit` itself is not calibrated and so it is possible to set either the `base_link` to `sensor_kit` or the `sensor_kit` to `lidar_frame` arbitrarily and derive the remaining tf from the calibration (this is the actual output of our tool). For example, a convenient choice is to set the `sensor_kit` equal to the `lidar_frame`

**Comment by ismetatabay** [comment]
I'll try the case which you mentioned, thank you very much for the reply. I will also inform latest situation :+1:
